export const API_ENDPOINTS = {
  TEMPLATES: '/api/templates',
  SAVE_TEMPLATE: '/api/save-template',
  DELETE_TEMPLATE: '/api/delete-template',
  CREATE_TEMPLATE: '/api/create-template',
  TEST_DATA: '/api/test-data',
  RUN_TESTS: '/api/run-tests',
  TEST_STATUS: '/api/test-status',
  REPORTS: '/api/reports',
  DELETE_REPORT: '/api/delete-report',
  LOGS: '/api/logs',
  DELETE_LOG: '/api/delete-log',
  TEST_PLANS: '/api/test-plans',
  DELETE_TEST_PLAN: '/api/delete-test-plan',
  SCREENSHOTS: '/api/screenshots',
  SETTINGS: {
    API_KEY: '/api/settings/api-key',
    TEST_API_KEY: '/api/settings/test-api-key',
    RESTORE_DEFAULT: '/api/settings/restore-default-key',
    USAGE: '/api/settings/usage',
    AUTO_TEST: '/api/settings/auto-test',
    API_STATUS: '/api/settings/api-status',
  },
}
